# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gear.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added', models.DateTimeField(verbose_name='date added')),
                ('manufacture_year', models.DateField(verbose_name='manufactured')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=2000)),
                ('tech_details', models.CharField(max_length=2000)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('rack_units', models.PositiveSmallIntegerField(null=True)),
                ('serial_no', models.CharField(max_length=500)),
                ('form_factor', models.CharField(choices=[(0, 'rack'), (1, 'desktop')], max_length=20)),
                ('state', models.CharField(choices=[(0, 'bad'), (1, 'ok'), (2, 'mint')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GearImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=gear.models.upload_gear_image)),
                ('gear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_image', to='gear.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('upload', models.FileField(upload_to=gear.models.upload_manual)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals_added', to=settings.AUTH_USER_MODEL)),
                ('gear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='gear.Gear')),
            ],
        ),
    ]
