# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20170306_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='form_factor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'rack'), (1, 'desktop')]),
        ),
        migrations.AlterField(
            model_name='gear',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'bad'), (1, 'ok'), (2, 'mint')]),
        ),
    ]
