# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_auto_20170306_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(choices=[(0, 1980), (1, 1981), (2, 1982), (3, 1983), (4, 1984), (5, 1985), (6, 1986), (7, 1987), (8, 1988), (9, 1989), (10, 1990), (11, 1991), (12, 1992), (13, 1993), (14, 1994), (15, 1995), (16, 1996), (17, 1997), (18, 1998), (19, 1999), (20, 2000), (21, 2001), (22, 2002), (23, 2003), (24, 2004), (25, 2005), (26, 2006), (27, 2007), (28, 2008), (29, 2009), (30, 2010), (31, 2011), (32, 2012), (33, 2013), (34, 2014), (35, 2015), (36, 2016)]),
        ),
    ]
