# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import gear.models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_auto_20170306_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='main_image',
            field=models.ImageField(default=1, upload_to=gear.models.upload_gear_image),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gear',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(choices=[(0, 1968), (1, 1969), (2, 1970), (3, 1971), (4, 1972), (5, 1973), (6, 1974), (7, 1975), (8, 1976), (9, 1977), (10, 1978), (11, 1979), (12, 1980), (13, 1981), (14, 1982), (15, 1983), (16, 1984), (17, 1985), (18, 1986), (19, 1987), (20, 1988), (21, 1989), (22, 1990), (23, 1991), (24, 1992), (25, 1993), (26, 1994), (27, 1995), (28, 1996), (29, 1997), (30, 1998), (31, 1999), (32, 2000), (33, 2001), (34, 2002), (35, 2003), (36, 2004), (37, 2005), (38, 2006), (39, 2007), (40, 2008), (41, 2009), (42, 2010), (43, 2011), (44, 2012), (45, 2013), (46, 2014), (47, 2015), (48, 2016), (49, 2017)]),
        ),
    ]
